### ISSUE TITLE
When using Password Keychain, the UITextField-Navigation is still appears at the bottom (iPhone X)

### ISSUE THREAD

**Issue by Idomo** [T-Pham/UITextField-Navigation#20]
Hi,
When I have 2 `UITextField`s (email & password) and I'm focusing one of them, I have an option to choose password from the iCloud Password Keychain and then the keyboard is going down, but the UITextField-Navigation is still appear at the bottom.

*Note that I have also 1Password activated as an source of passwords (so I have `ActionSheet` to choose between it and the build-in Keychain, and there you can see the problem).
Also note that I'm using iPhone X on iOS 12 (I don't know if it's only happens with the X or also with other screens).

Of course this is only a tiny UI issue so this is in low priority, but just posting it here if you'll find some time in the further and you'll want to fix it ;)

Thanks,
Ido.

**Comment by T-Pham** [comment]
Hi @Idomo, thanks for creating an issue.

Apparently this is just the way iOS handles the keyboard and the inputAccessoryView. There would be nothing we can or should do about it. The same behaviour happens when we use external keyboard. For the case with external keyboard, I guess the inputAccessoryView should be visible because there may be custom actions, such as copy/paste, that should always be accessible there.

**Comment by Idomo** [comment]
Got it :)
